version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fuel_management
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "89:3000"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fuel_management
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      PORT: 3000
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "88:80"
    depends_on:
      - backend

volumes:
  db_data: 